spring:
  application:
    name: message-producer

management:
  endpoints:
    web:
      exposure:
        include: '*'
  # Needed for kubernetes cloud configmap
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true

message:
  greeting: "Greeting from application.yml"
  farewell: "Farewell from application.yml"

#logging:
#  file: message-producer.log