spring:
  application:
    name: message-producer

# Needed for kubernetes cloud configmap
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

#logging:
#  file: message-producer.log