apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: message-producer
build:
  artifacts:
  - image: sandeepbhardwaj/message-producer
deploy:
  kubectl:
    manifests:
    - deploy/deployment.yml
