apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: message-producer
build:
  artifacts:
  - image: sandeepbhardwaj/message-producer
    docker:
      dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - deploy/config.yml
      - deploy/deployment.yml
